### ISSUE TITLE
no-unused-expressions

### ISSUE THREAD

**Issue by robmcguinness** [Availity/eslint-config-availity#11]
```yaml
no-unused-expressions:
    - 2
    - allowTernary: true
      allowShortCircuit: true
```
