### ISSUE TITLE
Relax jsx-a11y/label-has-associated-control

### ISSUE THREAD

**Issue by robmcguinness** [Availity/eslint-config-availity#228]
Airbnb config overrides the default rule `label-has-associated-control` rule from `eslint-plugin-jsx-a11y` where the input must BOTH be nested inside the label and also be for/ID-linked. According to https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/issues/718 simply having IDs linked is enough to be compliant. A lot of the Tailwind examples using linked IDs and not nested so it is better to override rule.

```yaml
rules:
    jsx-a11y/label-has-associated-control:
    - 2
    - required:
        some:
        - nesting
        - id
```
