### ISSUE TITLE
Leverage 3rd party maintained eslint configuration

### ISSUE THREAD

**Issue by robmcguinness** [Availity/eslint-config-availity#5]
Instead of maintaining all the rules by hand possibly leverage:

- https://github.com/Flet/eslint-config-semistandard
- https://github.com/feross/eslint-config-standard
- https://github.com/airbnb/javascript

**Comment by robmcguinness** [comment]
[standard/eslint-config-standard#82](https://github.com/standard/eslint-config-standard/issues/82) seems to have stalled.  Move to `eslint-config-airbnb-base`?

**Comment by robmcguinness** [comment]
Suggested rules:

```
rules:
  no-param-reassign: 0
  consistent-return: 0
  arrow-parens: ['error', 'as-needed']
```
