### ISSUE TITLE
Leverage import/core-modules for npm packages provided by framework

### ISSUE THREAD

**Issue by robmcguinness** [Availity/eslint-config-availity#9]
```yaml
settings:
  import/core-modules:
    - react-hot-loader
```

`react-hot-loader` is provided by `availity-workflow-react` and it would be nice for the import rules to account for this vs flagging an error.
